name: Gradle Build with GraalVM

on:
  push:
    branches:
      - master # Trigger the action only on master branch
  pull_request:
    branches:
      - master # Also trigger on pull requests to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17.0.7' # for a specific JDK 17; or '17' for the latest JDK 17
        distribution: 'graalvm' # New 'distribution' option

    - name: Set up environment for GraalVM
      run: |
        echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        echo "PATH=${JAVA_HOME}/bin:${PATH}" >> $GITHUB_ENV

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    # Optional: If you want to run tests or any other tasks, you can add them similarly
    #- name: Test with Gradle
    #  run: ./gradlew test
